---
# tasks file for kube-worker
- name: Copying kubeadm init response token to worker nodes
  copy: src={{ token_file }} dest=pod_network_token

- name: Copying kube config to worker nodes
  copy: src={{ kube_conf_file }} dest=kube_config

- name: Copying .kube/config
  shell: |
    mkdir -p $HOME/.kube
    sudo cp -f kube_config $HOME/.kube/config
    sudo chown $(id -u):$(id -g) $HOME/.kube/config
- name: Joining worker nodes with kubernetes master
  shell: |
    kubeadm reset -f
    cat pod_network_token | tail -2 > kube-join.sh
    sh kube-join.sh
  become_user: root
